const std = @import("std");
const meta = @import("meta.zig");

/// Generates a Bash completion script for command/struct T.
pub fn generateBash(comptime T: type, app_name: []const u8, writer: anytype) !void {
    try writer.print("#!/usr/bin/env bash\n", .{});
    try writer.print("# Bash completion for {s} generated by zcli\n\n", .{app_name});
    try writer.print("_{s}_completion() {{\n", .{app_name});
    try writer.print("    local cur prev opts\n", .{});
    try writer.print("    COMPREPLY=()\n", .{});
    try writer.print("    cur=\"${{COMP_WORDS[COMP_CWORD]}}\"\n", .{});
    try writer.print("    prev=\"${{COMP_WORDS[COMP_CWORD-1]}}\"\n\n", .{});

    if (comptime meta.isTaggedUnion(T)) {
        try writer.print("    local subcommands=\"", .{});
        const u_fields = @typeInfo(T).@"union".fields;
        inline for (u_fields, 0..) |uf, idx| {
            const cmd_name = meta.toKebabCase(uf.name);
            if (idx > 0) try writer.print(" ", .{});
            try writer.print("{s}", .{cmd_name});
        }
        try writer.print("\"\n\n", .{});

        try writer.print("    if [[ ${{COMP_CWORD}} -eq 1 ]] ; then\n", .{});
        try writer.print("        COMPREPLY=( $(compgen -W \"${{subcommands}} -h --help -V --version\" -- ${{cur}}) )\n", .{});
        try writer.print("        return 0\n", .{});
        try writer.print("    fi\n", .{});
    } else if (comptime meta.isStruct(T)) {
        try writer.print("    opts=\"", .{});
        const struct_fields = @typeInfo(T).@"struct".fields;
        inline for (struct_fields) |f| {
            if (!meta.isPositionalField(T, f.name)) {
                const flag_name = meta.toKebabCase(f.name);
                const short_char = meta.getShortChar(T, f.name);
                try writer.print("--{s} ", .{flag_name});
                if (short_char) |sc| {
                    try writer.print("-{c} ", .{sc});
                }
            }
        }
        try writer.print("-h --help -V --version\"\n\n", .{});
        try writer.print("    COMPREPLY=( $(compgen -W \"${{opts}}\" -- ${{cur}}) )\n", .{});
        try writer.print("    return 0\n", .{});
    }

    try writer.print("}}\n\n", .{});
    try writer.print("complete -F _{s}_completion {s}\n", .{ app_name, app_name });
}

/// Generates a Fish completion script for command/struct T.
pub fn generateFish(comptime T: type, app_name: []const u8, writer: anytype) !void {
    try writer.print("# Fish completion for {s} generated by zcli\n\n", .{app_name});

    if (comptime meta.isTaggedUnion(T)) {
        const u_fields = @typeInfo(T).@"union".fields;
        inline for (u_fields) |uf| {
            const cmd_name = meta.toKebabCase(uf.name);
            const help_text = meta.getHelpText(T, uf.name) orelse "";
            try writer.print("complete -c {s} -n \"__fish_use_subcommand\" -a \"{s}\" -d \"{s}\"\n", .{
                app_name,
                cmd_name,
                help_text,
            });
        }
    } else if (comptime meta.isStruct(T)) {
        const struct_fields = @typeInfo(T).@"struct".fields;
        inline for (struct_fields) |f| {
            if (!meta.isPositionalField(T, f.name)) {
                const flag_name = meta.toKebabCase(f.name);
                const short_char = meta.getShortChar(T, f.name);
                const help_text = meta.getHelpText(T, f.name) orelse "";

                try writer.print("complete -c {s} -l {s}", .{ app_name, flag_name });
                if (short_char) |sc| {
                    try writer.print(" -s {c}", .{sc});
                }
                if (!meta.isBool(f.type)) {
                    try writer.print(" -r", .{});
                }
                if (help_text.len > 0) {
                    try writer.print(" -d \"{s}\"", .{help_text});
                }
                try writer.print("\n", .{});
            }
        }
    }

    try writer.print("complete -c {s} -l help -s h -d \"Print help information\"\n", .{app_name});
    try writer.print("complete -c {s} -l version -s V -d \"Print version information\"\n", .{app_name});
}

/// Generates a Zsh completion script for command/struct T.
pub fn generateZsh(comptime T: type, app_name: []const u8, writer: anytype) !void {
    try writer.print("#compdef {s}\n\n", .{app_name});
    try writer.print("# Zsh completion for {s} generated by zcli\n\n", .{app_name});
    try writer.print("_{s}() {{\n", .{app_name});

    if (comptime meta.isTaggedUnion(T)) {
        try writer.print("    local -a commands\n", .{});
        try writer.print("    commands=(\n", .{});
        const u_fields = @typeInfo(T).@"union".fields;
        inline for (u_fields) |uf| {
            const cmd_name = meta.toKebabCase(uf.name);
            const help_text = meta.getHelpText(T, uf.name) orelse "";
            try writer.print("        \"{s}:{s}\"\n", .{ cmd_name, help_text });
        }
        try writer.print("    )\n\n", .{});
        try writer.print("    _arguments \\\n", .{});
        try writer.print("        '(-h --help)'{{-h,--help}}'[Print help]' \\\n", .{});
        try writer.print("        '(-V --version)'{{-V,--version}}'[Print version]' \\\n", .{});
        try writer.print("        '1: :->cmd' \\\n", .{});
        try writer.print("        '*:: :->args'\n\n", .{});
        try writer.print("    case $state in\n", .{});
        try writer.print("        cmd)\n", .{});
        try writer.print("            _describe -t commands '{s} commands' commands\n", .{app_name});
        try writer.print("            ;;\n", .{});
        try writer.print("    esac\n", .{});
    } else if (comptime meta.isStruct(T)) {
        try writer.print("    _arguments -s \\\n", .{});
        const struct_fields = @typeInfo(T).@"struct".fields;
        inline for (struct_fields) |f| {
            if (!meta.isPositionalField(T, f.name)) {
                const flag_name = meta.toKebabCase(f.name);
                const short_char = meta.getShortChar(T, f.name);
                const help_text = meta.getHelpText(T, f.name) orelse "";

                if (short_char) |sc| {
                    if (meta.isBool(f.type)) {
                        try writer.print("        '(-{c} --{s})'{{-{c},--{s}}}'[{s}]' \\\n", .{
                            sc, flag_name, sc, flag_name, help_text,
                        });
                    } else {
                        try writer.print("        '(-{c} --{s})'{{-{c},--{s}}}'[{s}]:value:' \\\n", .{
                            sc, flag_name, sc, flag_name, help_text,
                        });
                    }
                } else {
                    if (meta.isBool(f.type)) {
                        try writer.print("        '--{s}[{s}]' \\\n", .{ flag_name, help_text });
                    } else {
                        try writer.print("        '--{s}[{s}]:value:' \\\n", .{ flag_name, help_text });
                    }
                }
            }
        }
        try writer.print("        '(-h --help)'{{-h,--help}}'[Print help]' \\\n", .{});
        try writer.print("        '(-V --version)'{{-V,--version}}'[Print version]'\n", .{});
    }

    try writer.print("}}\n\n", .{});
    try writer.print("_{s} \"$@\"\n", .{app_name});
}

// --- Unit Tests for Completion ---
test "completion: bash, zsh, and fish generator" {
    const testing = std.testing;

    const ServerConfig = struct {
        port: u16 = 8080,
        host: []const u8 = "127.0.0.1",
        verbose: bool = false,

        pub const zcli = .{
            .name = "my-daemon",
            .short = .{ .port = 'p', .verbose = 'v', .host = 'h' },
            .help = .{ .port = "Port to bind", .host = "Host address" },
        };
    };

    var buf: [4096]u8 = undefined;

    // Bash
    {
        const help_mod = @import("help.zig");
        var writer = help_mod.BufferWriter.init(&buf);
        try generateBash(ServerConfig, "my-daemon", &writer);
        const script = writer.getWritten();
        try testing.expect(std.mem.indexOf(u8, script, "_my-daemon_completion()") != null);
        try testing.expect(std.mem.indexOf(u8, script, "--port") != null);
        try testing.expect(std.mem.indexOf(u8, script, "complete -F _my-daemon_completion my-daemon") != null);
    }

    // Fish
    {
        const help_mod = @import("help.zig");
        var writer = help_mod.BufferWriter.init(&buf);
        try generateFish(ServerConfig, "my-daemon", &writer);
        const script = writer.getWritten();
        try testing.expect(std.mem.indexOf(u8, script, "complete -c my-daemon -l port -s p -r -d \"Port to bind\"") != null);
    }

    // Zsh
    {
        const help_mod = @import("help.zig");
        var writer = help_mod.BufferWriter.init(&buf);
        try generateZsh(ServerConfig, "my-daemon", &writer);
        const script = writer.getWritten();
        try testing.expect(std.mem.indexOf(u8, script, "#compdef my-daemon") != null);
        try testing.expect(std.mem.indexOf(u8, script, "_my-daemon()") != null);
    }
}
